### ISSUE TITLE
Design feedback 29/04

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/workstreams-app#54]
- [x] Remove role functionality (from create modal and tag) #62 

- [x] explore page #61 
    - [x] remove buttons from card
    - [x] make consistent timeframe + rate component
    - [x] remove active workstreams
    - [x] can we show a status of the workstream
    - [x] could add the banner with x open applications
    - [x] can we show total grant rate and day rate

- [x] create flow
    - [x] remove role options #62 
    - [x] wysiwyg markdown support?
    - [ ] see issues for improvements
    - [x] show calculated day rate #61 
    - [ ] Can we "onboard"/"handhold" better

- [ ] dashboard
    - [ ] order cards by newest first
    - [x] create sections for all states of a card (Jason) #52 

- [x] apply modal
    - [ ] handhold more
    - [ ] explain counter offer

- [ ] detail page
    - [ ] state with one accepted application (Julien)
        - [ ] START STREAMING STATE

- [ ] MISSING FLOWS
    - [ ] set terms flow
    - [ ] propose Workstream
        - [ ] we can approach it through the profile page 
        - [ ] do you propose and apply
    - [ ] editing non on chain data

**Comment by juliendonck** [comment]
@efstajas @brandonhaslegs I dumped everything here, we can convert these to issues and assign ourselves when we pick up any of the work.

**Comment by efstajas** [comment]
🔥🔥🔥🔥
